Clinical-Genomics/patientMatcher

patientMatcher/cli/add.py, patientMatcher/parse/patient.py, patientMatcher/utils/load.py, tests/backend/test_backend_patient.py, tests/match/test_GT_matching.py
This will be useful when performing phenotype matching.
=> Add option to compute monarch phenotypes when patients are added to db

patientMatcher/cli/add.py, patientMatcher/match/genotype_matcher.py, patientMatcher/match/phenotype_matcher.py, patientMatcher/parse/monarch.py, patientMatcher/parse/patient.py, tests/backend/test_backend_patient.py, tests/match/test_pheno_matching.py
Takes into account:
1. HPO terms (features) 
2. Diagnoses (OMIM)
3. Computed diagnoses (using Monarch Phenotype Profile Builder )
HPO terms match is responsible for half of the phenotype score.
If OMIM diagnoses are available they count for 25% of the phenotype score (25% Monarch terms)
If OMIM diagnoses are not available then Monarch terms are responsible for 50% of the phenotype score.
=> Wrote a decent phenotype matching algorithm

patientMatcher/match/genotype_matcher.py, patientMatcher/parse/patient.py, tests/match/test_GT_matching.py
=> Simplified genotype matching algorithm

instance/config.py, patientMatcher/cli/commands.py, patientMatcher/match/genotype_matcher.py, patientMatcher/match/handler.py, patientMatcher/match/phenotype_matcher.py, patientMatcher/parse/monarch.py, tests/backend/test_backend_patient.py, tests/match/test_GT_matching.py, tests/match/test_matching_handler.py, tests/match/test_pheno_matching.py
Created a matching handler that combined the phenotype and genotype matching algorithms.
Added a test for it.
Commenting the tests for Monarch phenotype computing for now because the service is down!
=> Combine pheno geno algorithms

patientMatcher/__init__.py, patientMatcher/match/phenotype_matcher.py, patientMatcher/parse/patient.py, patientMatcher/server/views.py, patientMatcher/utils/phenotype.py, tests/match/test_GT_matching.py
@blueprint.route('/patient/add')
def add():
return "Patient add"
@blueprint.route('/patient/delete')
def delete():
return "Patient delete"
@blueprint.route('/patient/view')
def view():
return "Get all patients in db"
@blueprint.route('/patient/matches')
def matches():
return "Get all matches for a patient ID"
@blueprint.route('/match/external')
def match_external():
return "Match patient against external nodes"
@blueprint.route('/match/internal')
def match_internal():
return "Match patient against patients within same node"
=> added all the methods that I want to be present in server

patientMatcher/auth/auth.py, patientMatcher/constants/__init__.py, patientMatcher/match/genotype_matcher.py, patientMatcher/match/phenotype_matcher.py, patientMatcher/parse/patient.py, patientMatcher/server/controllers.py, patientMatcher/server/views.py, patientMatcher/utils/patient.py, tests/conftest.py, tests/match/test_matching_handler.py, tests/test_server/test_server_responses.py, tests/utils/test_patient.py
Started working on the server responses. Created a view to get a list of all patients on the server if the client is authorized. With tests!
=> Implemented method to get all patients if client is authorized

patientMatcher/cli/add.py, patientMatcher/cli/commands.py, patientMatcher/utils/add.py, requirements-dev.txt, tests/backend/test_backend_patient.py, tests/backend/test_nodes.py, tests/cli/test_commands.py, tests/conftest.py, tests/match/test_pheno_matching.py, tests/server/test_server_responses.py
Added a bunch of tests, especially for the cli
=> Improve test coverage

patientMatcher/constants/__init__.py, patientMatcher/parse/patient.py, patientMatcher/resources/api.json, patientMatcher/server/controllers.py, patientMatcher/server/views.py, patientMatcher/utils/add.py, requirements.txt, tests/server/test_server_responses.py
Validation using the MME API schema (as reference server).
Test that checks id user is authenticated (via token), if patient syntax is valid and if patients are updated after another post request to the same API
=> Submit patients to the API using POST requests

patientMatcher/match/handler.py, patientMatcher/parse/patient.py, patientMatcher/server/controllers.py, patientMatcher/server/views.py, tests/conftest.py, tests/server/test_server_responses.py
Created the code to accept POST request with query patients and returns server response with patients similar to the query one.
- Uses token auth
- Checks json syntax
- Validates json against MME API - in both senses (request and response)
- Added a dedicated test
=> Matchpatient view

tests/server/test_server_responses.py
Testing the response validation failure
=> test validation failure

patientMatcher/cli/add.py, patientMatcher/cli/commands.py, patientMatcher/match/handler.py, patientMatcher/parse/patient.py, patientMatcher/server/views.py, patientMatcher/utils/add.py, tests/backend/test_backend_patient.py, tests/backend/test_nodes.py, tests/cli/test_commands.py, tests/conftest.py, tests/server/test_server_responses.py
=> Trigger an external matching request to connected nodes when a patient is added or updated

README.md, patientMatcher/match/handler.py, patientMatcher/server/views.py, tests/conftest.py, tests/server/test_server_responses.py
=> Endpoint to get matches by patient id

README.md, patientMatcher/cli/remove.py, tests/cli/test_commands.py
=> Remove clients and  connected nodes by command line

README.md, instance/config.py, patientMatcher/__init__.py, patientMatcher/match/handler.py, patientMatcher/server/views.py, tests/server/test_server_responses.py
Updated the readme and relative test.
Introduces a check for valid config parameters before running the app
=> Customize max number of returned results

README.md, patientMatcher/cli/add.py, patientMatcher/cli/commands.py, patientMatcher/server/controllers.py, patientMatcher/server/views.py, tests/cli/test_commands.py, tests/conftest.py, tests/server/test_server_responses.py
- I've first created an endpoint to show clients which nodes are available (with test and documentation)
- The list of nodes will be returned only if client if authorized
=> View connected nodes

README.md, patientMatcher/match/handler.py, patientMatcher/server/controllers.py, patientMatcher/server/views.py, tests/server/test_server_responses.py
=> External matching by specifying a node

patientMatcher/match/handler.py, patientMatcher/server/views.py, patientMatcher/utils/notify.py, tests/conftest.py, tests/match/test_matching_handler.py
fix #54. Saving match results in this format:
=> Group matches by node

patientMatcher/cli/commands.py, patientMatcher/parse/monarch.py, patientMatcher/utils/notify.py, tests/utils/test_notify.py
fix #65
After this update email notifications will display the entire info of each patient in match results.
=> Exaustive notifications

patientMatcher/server/controllers.py, patientMatcher/server/views.py, tests/server/test_server_responses.py
=> Added a heartbeat

patientMatcher/instance/config.py, patientMatcher/match/handler.py
Avoid returning match results with patient score = 0
=> return only matches with positive score

patientMatcher/match/phenotype_matcher.py, tests/match/test_pheno_matching.py
=> Pheno rank all patients

patientMatcher/match/genotype_matcher.py
=> Fixes a bug in genotype matching

Dockerfile, patientMatcher/match/handler.py, patientMatcher/server/views.py
Some more Dockerfile changes leading up to the workshop.
I also got mme-async and patientMatcher to complete query / response with each other! While I was doing that I found a couple bugs on handling the async response. I also tried to add a little extra error handling when the remote nodes can't process a match request, but it broke the tests so I rolled it back.
=> Docker improvements, extra error handling

CHANGELOG.md, README.md, patientMatcher/instance/config.py, patientMatcher/match/handler.py, patientMatcher/server/views.py, tests/match/test_matching_handler.py
So that only match results above this threshold will be returned. Setting this threshold to 0 in the basic conf file. It can be customized by system admin!
fix #105
=> Introduce a score threshold params in config and result handler

patientMatcher/cli/add.py, patientMatcher/instance/config.py, patientMatcher/match/handler.py, patientMatcher/server/controllers.py, patientMatcher/server/views.py, patientMatcher/utils/add.py, tests/backend/test_backend_patient.py, tests/match/test_GT_matching.py, tests/match/test_matching_handler.py, tests/match/test_pheno_matching.py, tests/server/test_server_responses.py, tests/utils/test_patient.py
fix #111 and temporary fix #112
=> Improve external matching error handling

patientMatcher/parse/patient.py, tests/conftest.py, tests/server/test_server_responses.py
=> Fix missing missing patients id in results

patientMatcher/match/genotype_matcher.py, patientMatcher/parse/patient.py, tests/parse/test_parse_patient.py
Take into account of genes described by ensembl id when computing GT similarity
=> fix patient score taking into account ensembl genes

README.md, patientMatcher/cli/add.py, patientMatcher/match/genotype_matcher.py, patientMatcher/parse/patient.py, patientMatcher/server/controllers.py, patientMatcher/utils/add.py, patientMatcher/utils/ensembl_rest_client.py, patientMatcher/utils/gene.py, tests/backend/test_backend_patient.py, tests/cli/test_commands.py, tests/conftest.py, tests/match/test_GT_matching.py, tests/match/test_matching_handler.py, tests/match/test_pheno_matching.py, tests/parse/test_parse_patient.py, tests/server/test_server_responses.py, tests/utils/test_gene.py
=> Use ensembl gene IDs

patientMatcher/utils/notify.py
Fixes patially #124
To be tested on stage
=> Add email info (if available) to notification email

patientMatcher/server/controllers.py, patientMatcher/server/views.py
=> Save only matches with results or errors

CHANGELOG.md, patientMatcher/constants/__init__.py
=> Fixed name of HPO resource file on Jenkins Lab repo

CHANGELOG.md, README.md, patientMatcher/server/views.py, requirements-dev.txt, tests/server/test_server_responses.py
=> Open metrics view and update test and documentation

CHANGELOG.md, README.md, patientMatcher/instance/config.py
Fix #176 and fix #176
Nothing to test, it's just documentation.
=> Switch coverage badge to codecov and add admin notifications howto

patientMatcher/match/phenotype_matcher.py, patientMatcher/server/__init__.py, patientMatcher/server/extensions.py, patientMatcher/utils/hpo.py, tests/match/test_matching_handler.py, tests/server/test_create_app.py
- Move the creation of the HPO ontology to an internal class - now the HPO is handled by an external library ([patient-similarity](https://github.com/Clinical-Genomics/patient-similarity/blob/8b7d14fe915f25e70fcef92f81954849e77aa97b/patient_similarity/hpo.py#L148))
- Initialize the HPO just once, when the app is launched, and not every time a phenotype matching occurs
- Use the in-house HPO in the phenotype similarity (still handled by patient-similarity, for now)
`bash servers/resources/clinical-db.scilifelab.se/update-pmatcher-stage.sh implement_hpo_matching`
- Try to run matches for a demo case (https://scout-stage.scilifelab.se/cust101/A1383)
=> Decouple HPO parsing and handling from external lib

CHANGELOG.md, patientMatcher/match/phenotype_matcher.py, patientMatcher/server/__init__.py, patientMatcher/server/extensions.py, patientMatcher/utils/disease.py, patientMatcher/utils/hpo.py
- Use internal module to organize the HPO info content (for phenotype matching) instead of the same module on patient-similarity
- On master branch, update resources first and then match a demo patient with diagnosis against the 50 test patient in demo dataset:
Example query:
```
curl -X POST \
-H 'X-Auth-Token: chiara' \
-H 'Content-Type: application/vnd.ga4gh.matchmaker.v1.0+json' \
-H 'Accept: application/vnd.ga4gh.matchmaker.v1.0+json' \
-d '{"patient":{
"id":"patient_id",
"contact": {"name":"Contact Name", "href":"mailto:contact_name@mail.com"},
"features":[{"id":"HP:0009623"}],
"genomicFeatures":[{"gene":{"id":"EFTUD2"}}],
"disorders": [{"id":"MIM:610536"}]
}}' 127.0.0.1:5000/match
```
- Match a patient with phenotype terms. 
- The matching results …
=> Decouple HPOIC (HPO info content) from Patient-Similarity (decouple patient-similarity 3)

.github/workflows/black.yml, CHANGELOG.md, README.md, docker-compose.yml, patientMatcher/cli/add.py, patientMatcher/server/views.py, patientMatcher/utils/add.py, patientMatcher/utils/delete.py, requirements.txt, setup.py, tests/backend/test_backend_patient.py, tests/cli/test_commands.py, tests/server/test_server_responses.py, tests/utils/test_delete.py, tests/utils/test_patient.py
- Fix #193 
- Create a demo user **DE**xter **MO**rgan with token **DEMO** when demo data is created
- Fix Readme file documentation and docker compose file accordingly
- run `pmatcher add demodata` and make sure that new collections `patients` and `clients` are created from scratch
=> Drop all collections and create demo client with add demodata command

.github/workflows/docker_build_n_publish.yml, .github/workflows/pypi_publish.yml, CHANGELOG.md
=> Create a - publish to PyPi- github action

CHANGELOG.md, README.md
- Improves the description of the software in the readme file
-No tests needed
=> Added software purpose and description of developers and the Stockholm node in README file

.github/workflows/vulture.yml, CHANGELOG.md, patientMatcher/cli/add.py, patientMatcher/cli/commands.py, patientMatcher/match/handler.py, patientMatcher/match/phenotype_matcher.py, tests/cli/test_add.py, tests/cli/test_commands.py, tests/conftest.py, tests/server/test_server_responses.py, tests/utils/test_notify.py, tests/utils/test_patient.py
- Removes some dead code
- Adds a [Vulture](https://github.com/anaynayak/python-vulture-action) GitHub action that flags unused code with 90% confidence
- Run automatic tests
- Make the that the new action works 
=> Remove dead code and add Vulture action

CHANGELOG.md, requirements.txt
- Fix #243 
`bash servers/resources/SERVER.scilifelab.se/update-[THIS_TOOL]-stage.sh [THIS-BRANCH-NAME]`
=> Freeze PyMongo lib to still support old MongoDb versions

.github/workflows/docker_build_n_publish_stage.yml, CHANGELOG.md
- Push the branch of a PR to Docker hub -->https://hub.docker.com/repository/docker/clinicalgenomics/patientmatcher-stage
- Open a new PR and make sure the branch ends up in Docker Hub
=> Docker deploy stage

CHANGELOG.md, patientMatcher/server/__init__.py
- Print database name used in connection when launching the app
- Fixed misleading initial debug message
- Launch the app
=> Improved initial debug messages

CHANGELOG.md, patientMatcher/instance/config.py, patientMatcher/server/controllers.py, patientMatcher/server/templates/index.html, patientMatcher/server/views.py
fix #103 
- Launch the server via docker-compose (docker-compose up)
- In a browser, go to http://localhost:8000
=> Created a landing page for PatientMatcher

CHANGELOG.md, patientMatcher/utils/notify.py, tests/utils/test_notify.py
- Fix#242
- Testing using unittests
=> Include software version in email notifications

CHANGELOG.md, tests/match/test_GT_matching.py, tests/match/test_matching_handler.py, tests/server/test_server_responses.py, tests/utils/test_ensembl_rest_api.py, tests/utils/test_gene.py, tests/utils/test_variant.py
Fix #265 
- Locally, go offline and run all tests
=> Mock ALL web services in tests -- FINAL

CHANGELOG.md, docker-compose.yml, patientMatcher/instance/config.py, patientMatcher/utils/notify.py, tests/server/test_create_app.py
Fix #268 
- Install the branch on cg-vm1 (check also the ENV vars used there) and test matching against other patients in patientmatcher and external nodes
- From scout stage on cg-vm1, launch matches against the Scout MME and an external server
=> Fix env vars parsing

CHANGELOG.md, patientMatcher/server/templates/index.html
Changed from this:
To this:
- Run server locally and check that it looks finw
=> Changed colors and upgraded icons of landing page

CHANGELOG.md, patientMatcher/server/__init__.py, patientMatcher/server/views.py, tests/server/test_create_app.py
- As best as I could, fix #276 
- Using a personal gmail account, trigger an error and check that the email is sent
- CI tests should also pass
=> Test admin notifications when app crashes

CHANGELOG.md, CITATION.cff, README.md
- Added paper to Zenodo as well --> https://zenodo.org/record/6340057#.Yih2sZPMI-Q
- Fix #281 
=> Update citation to point to paper

.github/workflows/pytest_codecov.yml, CHANGELOG.md
- Fix #287 
- Check that codecov github action works
=> Update codecov action to version 2

.github/workflows/black.yml, CHANGELOG.md
- Fix #291 
- All tests should pass
=> Upgrade black vesion in GitHub action

CHANGELOG.md, codecov.yml
- Fix #289 
- All GitHub actions included tests and coverage should pass
=> Created codecov config file

CHANGELOG.md, docs/phenotype_resources.md, mkdocs.yml
- Added docs on how to update resource files
- Run `mkdocs serve`
- Docs page should be available
=> Added docs on how to update phenotype resource files

CHANGELOG.md, patientMatcher/constants/__init__.py
- Fix #309 
- Automatic tests should work again
=> Fix link to phenotype_annotation.tab

CHANGELOG.md, patientMatcher/match/handler.py, patientMatcher/server/views.py, patientMatcher/utils/delete.py, patientMatcher/utils/patient.py
- Decreases software vulnerability.
Main branch:
This branch:
=> Decreased vulnerability by removing some server log messages

CHANGELOG.md, patientMatcher/server/templates/index.html, tests/server/test_create_app.py, tests/server/test_server_responses.py
- Fixed all problems reported as bugs by SonarCloud
Main branch:
- 
=> Fix sonarcloud bugz

CHANGELOG.md, patientMatcher/cli/update.py, patientMatcher/match/genotype_matcher.py, patientMatcher/match/handler.py, patientMatcher/parse/patient.py, patientMatcher/server/__init__.py, patientMatcher/server/controllers.py, patientMatcher/utils/disease.py, patientMatcher/utils/hpo.py, patientMatcher/utils/notify.py, patientMatcher/utils/stats.py, setup.py, tests/backend/test_backend_patient.py, tests/cli/test_add.py, tests/cli/test_commands.py, tests/cli/test_remove.py, tests/cli/test_update.py, tests/conftest.py, tests/match/test_pheno_matching.py, tests/server/test_server_responses.py, tests/utils/test_ensembl_rest_api.py, tests/utils/test_variant.py
=> Fix many code smells reported by SonarCloud

CHANGELOG.md, patientMatcher/cli/update.py, patientMatcher/constants/__init__.py, patientMatcher/resources/__init__.py, patientMatcher/utils/disease.py
- Fix #318 
- Type `pmatcher update resources`
- Launch the server
=> Switch from phenotype_annotation.tab to phenotype.hpoa

.github/workflows/black.yml, .github/workflows/flake8.yml, .github/workflows/pypi_publish.yml, CHANGELOG.md
- Fix #317 
`bash servers/resources/SERVER.scilifelab.se/update-[THIS_TOOL]-stage.sh [THIS-BRANCH-NAME]`
-
=> Replace deprecated version of Ubuntu in GitHub actions

.github/workflows/docker_build_n_publish_stage.yml, CHANGELOG.md, README.md
=> Fixed broken Build and publish to Docker stage badge

CHANGELOG.md, patientMatcher/utils/disease.py
- Fix #327 
- Download the latest resources
- Start demo server
=> Fix parsing of disease file and update resources

.github/workflows/pytest_codecov.yml, CHANGELOG.md, patientMatcher/resources/__init__.py
=> Remove deprecated pkg_resources

.github/workflows/pytest_codecov.yml, CHANGELOG.md, docs/conda_inst.md, pyproject.toml, uv.lock
- Install package using UV (updated also installation docs) (closes #348)
=> Install software via uv

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/other_issue.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
=> Custom issue and PR templates

CHANGELOG.md, RELEASE.md, uv.lock
- Closes #359 
- All tests should pass
=> Update resource files

.github/workflows/docker_build_n_publish.yml, .github/workflows/docker_build_n_publish_stage.yml, CHANGELOG.md, Dockerfile, Dockerfile-server
- Closes #367 
- Image quality should improve to A
=> Add supply chain attestation to Docker files

.github/workflows/pypi_publish.yml, CHANGELOG.md
- Fix #369 
- It should be pushed to PYPI
=> Fix broken publish to PyPI action
