- patientMatcher/server/controllers.py
- patientMatcher/server/views.py
- tests/server/test_server_responses.py
Authorized users can trigger searches on external nodes by providing the ID of a patient present in the database.
With test
> trigger matches on nodes using patient id

- README.md
- instance/config.py
- patientMatcher/__init__.py
- patientMatcher/server/controllers.py
- patientMatcher/server/views.py
- patientMatcher/utils/add.py
- patientMatcher/utils/notify.py
- requirements.txt
- tests/backend/test_backend_patient.py
- tests/cli/test_commands.py
- tests/conftest.py
- tests/server/test_init.py
- tests/server/test_server_responses.py
- tests/utils/test_notify.py
Added the option to send email notification upon patient matching.
If email params in configuration file are valid an email notification is sent in the following situations:
- A patient is added to the database and the add request triggers a search on external nodes producing at least one result (/patient/add endpoint).
- An external search is actively performed on connected nodes and returns at least one result (/match/external/<patient_id> endpoint).
- The server is interrogated by an external node and returns at least one result match (/match endpoint). In this case a match notification is sent to each contact of the result matches.
- An internal search is submitted to the server using a patient from the database (/match endpoint) and this search returns at least one match. In this …
> Notify matches

- patientMatcher/utils/notify.py
When patient in results is the same as the one used for query
> Avoid double notification

- README.md
- patientMatcher/match/handler.py
- patientMatcher/server/views.py
- tests/server/test_server_responses.py
- Fixed /matches/patient_id endpoint description in readme
- /matches/patient_id returned a list of lists for external matches. It's returning just a list of patients now
- /matches/patient_id endpoint returns a list of matches objects called "matches", instead of "results" now
> flattened out the matches result list and renamed results to matches

- README.md
- instance/config.py
- patientMatcher/match/handler.py
- patientMatcher/parse/patient.py
- patientMatcher/server/controllers.py
- patientMatcher/server/views.py
- patientMatcher/utils/stats.py
- tests/server/test_server_responses.py
fix #67.
With this fix the server will be returning all the mandatory and optional metrics described here: https://github.com/ga4gh/mme-apis/blob/master/metrics-api.md except for one: **numberOfFeatureSets** (which is a bit of a pain to calculate and is optional anyway).
Updated tests and readme. Server is returning metrics instead of a list of patient (improved security!)
> Add metrics

- instance/config.py
- patientMatcher/auth/auth.py
- patientMatcher/cli/add.py
- patientMatcher/match/handler.py
- patientMatcher/server/controllers.py
- patientMatcher/server/views.py
- patientMatcher/utils/add.py
- tests/backend/test_backend_patient.py
- tests/match/test_pheno_matching.py
- tests/server/test_server_responses.py
Send patientMatcher host in requests headers and return patientMatcher disclaimer along with match results in responses. 
Fix #66
> Introduce yourself in response

- README.md
- instance/config.py
- patientMatcher/server/views.py
- patientMatcher/utils/notify.py
- tests/utils/test_notify.py
Fix #74 . Makes it possible to choose to see complete patient data (complete phenotypes and genotypes) or only ID and contact info in email notifications.
> Email partial notifications

- Dockerfile
- README.md
- docker/entrypoint.sh
- instance/config.py
I wanted to play with getting both implementations running on a single docker bridge on Friday, so I put this together.
Some options you may have opinions on:
* `Dockerfile`:
* Set to use python 3.7.1, just since that was most recent. If you'd prefer a different version, can just change the `PYTHON_VERSION` var in Dockerfile
* `docker/entrypoint.sh`:
* initial user creation based on values in `instance/config.py`, but they're hardcoded and not read directly from the file. Since they're throwaway creds, I figured that wasn't too big of a deal, but may be worth changing
* adds initial demo data and token, but could have that be an extra step if a clean install is preferred
> Patient matcher dockerfile

- patientMatcher/parse/patient.py
- tests/server/test_server_responses.py
This PR makes the returned results gene field more user friendly by showing HGNC gene symbols along with Ensembl ids. 
Scout users will be thankful for this
> Save gene symbol as non standard field for all types of patients

- CHANGELOG.md
- patientMatcher/server/controllers.py
- patientMatcher/server/views.py
- patientMatcher/utils/add.py
- patientMatcher/utils/stats.py
- requirements-dev.txt
- requirements.txt
- tests/backend/test_backend_patient.py
- tests/backend/test_nodes.py
- tests/cli/test_commands.py
- tests/match/test_GT_matching.py
- tests/match/test_matching_handler.py
- tests/match/test_pheno_matching.py
- tests/server/test_server_responses.py
- tests/utils/test_notify.py
- Do not freeze pymongo, pytest and mongomock dependencies. Fix #142 and fix #143 
- Install on clinical-db stage
- Save patient data from Scout interface, check that adding a new patient with one or more variants works.
- Send a request for stats from the command line (curl) to get the server stats to make sure the info endpoint still works
- The above tests should work
> Unblock pymongo, pytest and mongomock dependencies

- CHANGELOG.md
- patientMatcher/utils/ensembl_rest_client.py
- patientMatcher/utils/gene.py
- tests/utils/test_ensembl_rest_api.py
fix #147 
Ensembl REST API might be needed to upload or match patients, but sometimes it's down. The result is that patients are not uploaded but it's not clear why. This code raise an exception with an informative message:
`Ensembl Rest API server returned error <status code> (it's probably down) and gene info could not be converted. Please try again later`
> Raise an exception with informative error message when Ensembl REST API is needed but down

- .dockerignore
- CHANGELOG.md
- Dockerfile
- README.md
- docker-compose.yml
- patientMatcher/instance/config.py
- patientMatcher/server/__init__.py
- setup.py
- Create a minimal Dockerfile that installs the app and its requirements in a container
- Wrote a docker-compose file that illustrates how to set up 3 containers:
- mongodb: starting a mongodb server with authentication (--auth option)
- pmatcher-cli: the a command-line app, which will connect to the server and populates it with demo data
- pmatcher-web: a web server running on localhost and port 27017.
fix #146
- The image is pushed to my Docker Hub (couldn't figure out how to push it to our organization yet)
`curl localhost:5000/metrics`
> Simplify Dockerfile and make it usable in production

- CHANGELOG.md
- docker-compose.yml
Pull the repo Docker image from Clinical Genomics Docker Hub.
> Pull Docker images from clinicalgenomics Docker Hub

- .github/workflows/docker_build_n_publish.yml
- CHANGELOG.md
- Dockerfile
Whenever a new version release is created, this actions builds the Docker image, tags it with 
- release version tag
- "latest"
- pushes the 2 tags to Docker Hub
> Created Docker build and push action

- CHANGELOG.md
- patientMatcher/match/genotype_matcher.py
- patientMatcher/match/phenotype_matcher.py
- patientMatcher/parse/patient.py
- tests/parse/test_parse_patient.py
Genes in genomic features can be specified by:
- ensembl gene ID
- entrez gene ID
- gene symbol from the HGNC database
But the use of ensembl gene ID is strongly encouraged and will become mandatory in 2.0. See [here](https://github.com/ga4gh/mme-apis/blob/master/search-api.md#genomicfeatures) for more info.
We user Ensembl Rest API to convert non-canonical gene IDs (gene symbols like LAMA1, or Entrez gene IDs) to Ensembl gene IDs. But sometimes the service is down so the app crashes. 
This PR fixes that behavior this way: whenever the service is down we won't convert and leave the gene ID as it is provided by the request.
- 
> Simplify gene symbol conversions and don't crash when Ensembl REST API is down

- CHANGELOG.md
- docker-compose.yml
- patientMatcher/utils/variant.py
- tests/utils/test_variant.py
- Adds the code to perform coordinates liftover between GRCh37 and GRCh38
> Coordinate liftover using Ensembl REST API

- CHANGELOG.md
- patientMatcher/match/genotype_matcher.py
- patientMatcher/match/phenotype_matcher.py
- patientMatcher/parse/patient.py
- patientMatcher/server/__init__.py
- requirements.txt
- tests/conftest.py
- tests/parse/test_parse_patient.py
- tests/utils/test_variant.py
Compare patients variants taking into account that the matching patient might have exactly the same variant but in another genome build. Fix #161 
```pmatcher add client -id dummynode -token custom_token -url whatevs.com```
```
curl -X POST \
-H 'X-Auth-Token: custom_token' \
-H 'Content-Type: application/vnd.ga4gh.matchmaker.v1.0+json' \
-H 'Accept: application/vnd.ga4gh.matchmaker.v1.0+json' \
-d '{"patient":{
"id":"patient_id",
"contact": {"name":"Contact Name", "href":"mailto:contact_name@mail.com"},
"features":[{"id":"HP:0011344"}],
"genomicFeatures":[{"gene":{"id":"GRIN2A"}, "variant":{"assembly":"GRCh38", "referenceName":"16", "start":9768996, "end":9768997,
"referenceBases":"T", "alternateBases":"C"}}]
}}' localhost:9020/match
```
This …
> Use variant liftover when comparing patients variants

- CHANGELOG.md
- patientMatcher/parse/patient.py
- patientMatcher/utils/variant.py
FIx #167 
Start demo app with demo data and run this request for a patient having a variant with no end coordinate:
```
curl -X POST \
-H 'X-Auth-Token: custom_token' \
-H 'Content-Type: application/vnd.ga4gh.matchmaker.v1.0+json' \
-H 'Accept: application/vnd.ga4gh.matchmaker.v1.0+json' \
-d '{"patient":{
"id":"patient_id",
"contact": {"name":"Contact Name", "href":"mailto:contact_name@mail.com"},
"features":[{"id":"HP:0011344"}],
"genomicFeatures":[{"gene":{"id":"GRIN2A"}, "variant":{"assembly":"GRCh38", "referenceName":"16", "start":9768996,
"referenceBases":"T", "alternateBases":"C"}}]
}}' localhost:9020/match
```
- The same results observed in testing this PR #165 
> Fix liftover error for variants without end coordinate

- .github/workflows/pytest_codecov.yml
- CHANGELOG.md
-  fix #174 
- All github actions tests should be successful
> Switch from coveralls to codecov in github actions

- .github/workflows/pytest_codecov.yml
- CHANGELOG.md
- patientMatcher/instance/config.py
- patientMatcher/server/__init__.py
- patientMatcher/server/views.py
- patientMatcher/utils/notify.py
- tests/server/test_create_app.py
- fix #170 
```
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 587
MAIL_USE_TLS = True
```
> Notify admins via email when app crashes

- CHANGELOG.md
- patientMatcher/cli/update.py
- patientMatcher/constants/__init__.py
Modify link to a deprecated phenotype_annotation.tab to point to an up-to-date resource hosted by Monarch. 
Checked and some entries are pretty new, like Feb 2021, so it's a good temporary fix I think.
- Partial fix #181 
> Download phenotype annotation file from Monarch

- CHANGELOG.md
- patientMatcher/server/__init__.py
- tests/server/test_create_app.py
-  Checks that these 2 required files are in place under resources before running non-testing app
- run `pmatcher run -p 9000` after removing one of these 2 files or noth
> Required downloading of hp.obo.txt and phenotype_annotation.tab.txt to run a non-testing app

- CHANGELOG.md
- patientMatcher/match/phenotype_matcher.py
- patientMatcher/server/__init__.py
- patientMatcher/server/extensions.py
- patientMatcher/utils/disease.py
- patientMatcher/utils/hpo.py
- tests/server/test_extensions.py
- Moves the parsing and creating of the Diseases class to the app extensions (decoupling from patient-similarity)
- Initialize Diseases just once, when the app is launched, and not every time a phenotype matching occurs
- Use the in-house Diseases for phenotype matching (still handled by patient-similarity algorithm, for now)
`bash servers/resources/clinical-db.scilifelab.se/update-pmatcher-stage.sh decouple_diseases`
> Moved the Diseases handler to the app (decoupled from Patient-similarity)

- CHANGELOG.md
- docker-compose.yml
- fix #188 
- launch the demo app with the command 'docker-compose up'
> Update docker-compose ports for app and database

- CHANGELOG.md
- docker-compose.yml
- run docker-compose up and make sure it works
> Modify connection Bridge address used in docker-compose

- .github/workflows/pytest_codecov.yml
- CHANGELOG.md
- Dockerfile
- README.md
- docker-compose.yml
- patientMatcher/match/phenotype_matcher.py
- patientMatcher/utils/patient.py
- requirements.txt
- tests/conftest.py
- tests/match/test_pheno_matching.py
And implement the HPO similarity calculation (simgic algorithm) locally.
Fix #172 
- Create a fresh conda environment with python 3.8
- Install the repo
- run a patient matching query with a patient that has HPO terms
- Match results should be returned. These matchings should have the same scores as master branch.
> Completely remove the patient-similarity dependency

- CHANGELOG.md
- containers/docker-compose_server_with_2_nodes.yml
fix #199 -> The other 2 nodes are other instances of patientMatcher.
The idea is to provide a complete example of a server containing demo data that:
- can be queried directly sending a request containing a json patient
- is capable of sending queries to other connected nodes searching for patients similar to a given patient id
- All containers with the command: `docker-compose --file containers/docker-compose_server_with_2_nodes.yml up`
- Edit scout config settings to integrate patientMatcher (pmatcher-web service):
```
MME_ACCEPTS = "application/vnd.ga4gh.matchmaker.v1.0+json"
MME_URL = "http://localhost:9020"
MME_TOKEN = "DEMO"
```
- Run scout and make sure that the MME options show the 2 connected nodes: `server-1` and `server-2`
- Add demo patient to …
> Created a demo docker-compose file with 2 other connected nodes

- CHANGELOG.md
- containers/docker-compose_server_with_2_nodes.yml
The current demo docker-compose with the 2 different connected nodes uses the same node id for both nodes: Since it's not possible to save in MongoDB 2 documents with the same ID, only the first node is created. All queries against the second node (using node 2 token) result in an not authorized response from the server:
This PR introduces different node IDs for different nodes
- run the docker-compose document: `docker-compose --file containers/docker-compose_server_with_2_nodes.yml up`
- launch a specific query on the second connected node
- The response should not be "not authorized"
> Use different ids for different connected nodes in demo docker-config

- CHANGELOG.md
- README.md
Fix #203 - The web container port launched with docker-compose is 9020 and not 27017 (that is the MongoDB port).
- No test, it's docs
> Fixed wed server container port launched with docker-compose

- CHANGELOG.md
- setup.py
There is a problem with the twine check command, so it's not possible to publish the package to PyPI:
With this fix:
> Fix setup file so it's processed by twine

- CHANGELOG.md
- patientMatcher/instance/config.py
- Fixes the DISCLAIMER syntax on this repo (partial fix #209)
- Bo test, it's just a change in a text.
> Fixed syntax in the disclaimer

- CHANGELOG.md
- containers/docker-compose_server_with_2_nodes.yml
- docker-compose.yml
- Removed a parameter the `--ensembl_genes` parameter that is no longer used by the `add demodata` command in all docker-compose files
- Launch Docker
- Run `docker-compose --file containers/docker-compose_server_with_2_nodes.yml up`
- Make sure that matching against the patients from these nodes returns results
> Removed a parameter the `--ensembl_genes` from `add demodata` in docker-compose

- CHANGELOG.md
- containers/docker-compose_server_with_2_nodes.yml
- containers/mongo-init.js
- docker-compose.yml
- Replaced vepo/mongo with mongo:4.4.9 in docker-compose files (fix #218)
- Created a mongo-init script for using authentication in docker-compose instances
This change was a bit tricky since **PatientMatcher is an app that is using MongoDB authentication** (is already like this in production), which means a database user and password params should be created and the app should be able to connect using these params. [vepo/mongo](https://github.com/vepo/mongo) was easy to use since you could provide all the params as environmental variables. Switching to the official mongo image I've found out that you can provide some scripts when launching the database that basically create the database user and password. I've followed these instructions: …
> Replaced vepo/mongo with mongo:4.4.9 and created mongo-init.js 

- CHANGELOG.md
- patientMatcher/cli/update.py
- patientMatcher/server/controllers.py
- patientMatcher/server/views.py
- patientMatcher/utils/patient.py
- tests/cli/test_update.py
- Improve views code by reusing a controllers function when request auth fails
- Bulk replace patients' contact info using the command line
Run the command:
```
pmatcher update contact -old-href 25105227 -href some.email@mail.com -name "Some Name"
```
> Bulk update patients contact info from the command line

- CHANGELOG.md
- README.md
- Add documentation on how to update patients' contact info using the command line
- No test needed, it just has to make sense.
> Add documentation on how to update patients' contact info using the command line

- CHANGELOG.md
- README.md
- patientMatcher/cli/update.py
- patientMatcher/parse/patient.py
- patientMatcher/server/controllers.py
- tests/cli/test_update.py
- tests/parse/test_parse_patient.py
- tests/server/test_server_responses.py
- Fix #229 -> Provided patient contact href must be either a valid URL or email address (format mailto:somename@test.se)
```
pmatcher add demodata
pmatcher run --port 9020
```
> Validate patient contact href when saving or updating patients

- CHANGELOG.md
- patientMatcher/utils/delete.py
- patientMatcher/utils/disease.py
- tests/backend/test_backend_patient.py
- tests/utils/test_delete.py
- Fix #214 
- Automatic tests should not complain about deprecated code any more. And they should pass of course!
> Fix deprecated code causing warnings during automatic tests

- CHANGELOG.md
- patientMatcher/cli/update.py
- patientMatcher/parse/patient.py
- patientMatcher/server/controllers.py
To reproduce:
- Load demo data
- Update contact href for one or more patients providing a new href with this format: `mailto:me@myself.com`
- Notice that the command will fail because the href passed to the validator will be mailto:mailto:me@myself.com
This PR fixes this problem
- Switch to this branch and try the commands above
> Do not duplicate mailto schema when patient contact email has already the right format

- .github/workflows/vulture.yml
- CHANGELOG.md
- patientMatcher/cli/add.py
- Vulture should not report any problems with setup.py in this PR
> Scan only changed files using vulture

- CHANGELOG.md
- Dockerfile
- docker-compose.yml
- patientMatcher/server/auto.py
- Fixes bug #245, that is preventing to run a prod app via Docker
- Modified the Dockerfile base image to use one that contains gunicorn
- Modified docker-compose file to illustrate running the dockerized app via Gunicorn
- In another terminal, run `curl localhost:9020/metrics` and it should return the server stats
<hr> 
- Remove all related containers, images and dangling stuff
- Having a running instance of MongoDB reachable on localhost, port 27017:
- Build the image: `docker build -t pm-image .`
- l**aunch a container to load the demo data into the database (cli)**: 
From a Mac terminal: `docker run --rm --env MONGODB_HOST=host.docker.internal --name pm-cli pm-image pmatcher add demodata`
From a linux terminal: `docker run --rm --network host --name pm-cli …
> Fix app wsgi and run Docker prod app via Gunicorn

- .github/workflows/docker_build_n_publish.yml
- .github/workflows/docker_build_n_publish_stage.yml
- CHANGELOG.md
- Dockerfile
- Dockerfile-server
- README.md
- docker-compose.yml
- patientMatcher/instance/config.py
- Created another Dockerfile to run the app via gunicorn
- Extended config file functionality to collect all required params from environment variables
- Modified README to describe the two distinct Dockerfiles
- Modified the docker-compose to provide an example on how to use the two Dockerfiles
- Modified  GitHub actions to push server image to Docker Hub when a pull request is opened or modified
- Modified  GitHub actions to push both standard and server image to Docker Hub when a new release is created
- Remove all old and dangling images from local Docker
- The tests above should be successful
> Dockerfile for pmatcher + Dockerfile for server

- CHANGELOG.md
- patientMatcher/instance/config.py
- patientMatcher/match/handler.py
- patientMatcher/server/views.py
- Fix #252
- Edit the config file with this param: `SCORE_THRESHOLD = 0.065` (stricter matching, will not return results with low score)
- Locally, load demo data into the database: `pmatcher add demodata`
- Start the demo server: `pmatcher run`
- From another shell window run a query that will not return results, **twice**:
```
curl -X POST \
-H 'X-Auth-Token: DEMO' \
-H 'Content-Type: application/vnd.ga4gh.matchmaker.v1.0+json' \
-H 'Accept: application/vnd.ga4gh.matchmaker.v1.0+json' \
-d '{"patient":{
"id":"patient_id",
"contact": {"name":"Contact Name", "href":"mailto:contact_name@mail.com"},
"features":[{"id":"HP:0001298"}]
}}' localhost:5000/match
```
- From another shell window run a query that will returns results:
```
curl -X POST \
-H 'X-Auth-Token: …
```
> Fix metrics

- CHANGELOG.md
- docker-compose.yml
- patientMatcher/instance/config.py
- patientMatcher/server/__init__.py
- patientMatcher/server/controllers.py
- tests/server/test_create_app.py
- tests/server/test_server_responses.py
> Fix heartbeat endpoint to return to return True or False if server is Prod or stage server

- .github/workflows/pytest_codecov.yml
- CHANGELOG.md
- requirements-dev.txt
Fix #258 
- Speeds up testing and avoid sending coverage report to Codecov multiple times per PR
- Check the GitHub actions
> Speed-up CI tests by caching installation of libs and splitting tests into groups

- CHANGELOG.md
- tests/parse/test_parse_patient.py
Fix #157 --> Do not rely on Ensembl online web services when running patient parsing tests (gene conversions, variants liftover)
> Mock Ensembl services (gene conversion and liftover) used in patient parsing tests

- CHANGELOG.md
- patientMatcher/cli/update.py
- tests/cli/test_update.py
- tests/parse/test_parse_patient.py
- Fixes the test that checks the availability of the phenotype resources online. Current main checks the file size of the online resources. In this branch the resources are mocked to point to the files present in this repo, in the "resources" folder.
> Mock the download of files containing phenotype resources in tests

- CHANGELOG.md
- patientMatcher/server/__init__.py
- Fix #279 
- Modify an endpoint to raise an error
- Modify config file with email params: server email, admin email, etc
- Launch the app and send a request to the endpoint that crashes
- Email should be sent to admin and it should contain the name of the database in use
> Include db name in crash email report

- CHANGELOG.md
- README.md
- Fix #298 --> App is now served on [port 8000](https://github.com/Clinical-Genomics/patientMatcher/blob/1f89c4ac3dc0db2c9f0fd579b66dbca804746e02/docker-compose.yml#L54) using docker-compose 
- Run` docker-compose up`
- Then on another terminal: `curl localhost:8000/metrics`
> Fixed ports used by app served using docker-compose in readme

- CHANGELOG.md
- patientMatcher/server/__init__.py
- patientMatcher/utils/disease.py
- patientMatcher/utils/hpo.py
- Fix #313 - it's not a bug, just an error in the log message!
- Locally, start the server on main branch and this branch and make sure that a number of parsed disease is shown when using this branch
> Display correct number of parsed diseases when server starts

- CHANGELOG.md
- patientMatcher/server/__init__.py
- FIx #319 
- Try to start the app with empty resource files
> Abort if phenotype terms are not correctly parsed from files

- .gitignore
- CHANGELOG.md
- patientMatcher/server/controllers.py
- patientMatcher/server/templates/index.html
- Fix #325 : unfortunately it is not possible to show the link to the connected nodes because the only link saved on the database right now is the link to the matching API. In the future we could introduce another database field to include a human-friendly link to the node page.
- Click on the i symbol in the connected nodes window:
> Display connected nodes info on index page

- .github/workflows/pytest_codecov.yml
- CHANGELOG.md
- docker-compose.yml
- requirements.txt
- Unfreeze PyMongo
- Use MongoDB version 7.0.2 in docker-compose.yml
- Execute tests using MongoDB 7.0.2
- Get the metrics from the server. From another terminal run:  curl localhost:8000/metrics
> Unfreeze PyMongo and run tests and docker-compose using MongoDB 7.0.2

- .github/workflows/pytest_codecov.yml
- CHANGELOG.md
- docker-compose.yml
- requirements.txt
- Unfreeze pymongo lib and upgrade MongoDB version to 7 in tests and docker-compose 
- Run docker-compose up and make sure the demo database gets populated
> generalize mongodb version in tests and docker-compose
